# Generated by Django 2.2.6 on 2019-11-10 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, default='anonymous', max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2019, 11, 10, 11, 37, 51, 802377), verbose_name='Date')),
                ('body', models.TextField()),
            ],
        ),
    ]
