# Generated by Django 2.2.7 on 2019-12-07 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='date_edited',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 15, 1, 37, 764868), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 15, 1, 37, 764868), verbose_name='Date'),
        ),
    ]
