# Generated by Django 2.2.7 on 2019-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191207_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edited',
            field=models.DateField(default='2019-12-07 15:09:43', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(default='2019-12-07 15:09:43', verbose_name='Date'),
        ),
    ]
