# Generated by Django 2.2.7 on 2019-12-07 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191207_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edited',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 15, 10, 25, 891986), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 15, 10, 25, 891986), verbose_name='Date'),
        ),
    ]
